### ISSUE TITLE
Sequences are not reusable?

### ISSUE THREAD

**Issue by SeanSobey** [mkloubert/node-enumerable#2]
Based on the example on the [REPL](https://mkloubert.github.io/demos/node-enumerable/):
```js
const seq = Enumerable.create(5979, 23979, null, '23979', 1781, 241279);

const a = seq.where((x) => x !== null)  // remove all elements that are (null)
   .skip(1)  // skip one element (5979)
   .take(3)  // take next remaining 3 elements (23979, 23979, 1781)
   .distinct()  // remove duplicates
   .select((x) => '' + x)
   .order();  // order by element ascending

const na = a.isEmpty();
a.toArray();
```
That returns an empty array.
Comment out the line `const na = a.isEmpty();` and it returns the expected results.

Is this the expected behaviour, that the sequences are not query-able multiple times? I see the sequence object has a `canReset` property and this is false, is that related?

**Comment by mkloubert** [comment]
@SeanSobey 

Yes, the behavior is expected, s. [that issue](https://github.com/mkloubert/node-enumerable/issues/1) ... so array like sequences behave as generators.
In your case, your sequence becomes a generator where it is not possible to count the element without iterate over them.

Make use of `makeResettable()` and `reset()` methods, so you can reset the "sequence pointer" after you have used `isEmpty()`.

**Comment by SeanSobey** [comment]
Ahh ok, thanks for the quick reply :)

I didn't notice `reset()` at the bottom of the docs, maybe worthwhile making a more verbose note about this, maybe in the `Usage` section?
